# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

import pandas as pd

configfile: "config.yaml"

sample = pd.read_table("samples.tsv",dtype=str)
bigwig1 = sample['bigwig1']
bigwig2 = sample['bigwig2']
labels1 = sample['labels1']
labels2 = sample['labels2']
bed = sample['bed']

rule all:
	input: 
	 "results/",
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

#include: "rules/common.smk"
#include: "rules/test.smk"
include: "rules/bigwig.summary.bed.smk"
#include: "rules/bigwig.summary.bins.smk"
#include: "rules/correlation.smk"
